### ISSUE TITLE
Add bios to project

### ISSUE THREAD

**Issue by hubyeti** [coa-dlu/github-for-developers-8#3]
We should all create great bios in this project. Make sure your bio includes:

         - [ ] Your name
         - [ ] Where you are from
         - [ ] A favorite food
         - [ ] A hobby

**Comment by coa-dlu** [comment]
![octocat](https://cloud.githubusercontent.com/assets/6741888/12533071/64232768-c1ea-11e5-9cbd-aeed35bab194.png)
here's the bios:
- coa-dlu
- coa
- ice-cream
- food tasting
